### ISSUE TITLE
Missing 'export' in index.d.ts

### ISSUE THREAD

**Issue by itaym** [yaohuangguan/react-dispatch#1]
declare const dispatcher: {
    dispatch: (event: string, data: any) => void;
    on: (event: string, callback: any) => void;
    once: (event: string, callback: any) => void;
    off: (event: any) => any;
};
Web storm inspector warn that dispatcher is not exported. If you add 'export' before the 'declare' to solves the issue.

**Comment by yaohuangguan** [comment]
Thx for the advice! I will create relevant fix.
